//
//  FieldTemplate.swift
//  Tetorinu
//
//  Created by 広瀬友哉 on 2024/09/23.
//

import SwiftUICore

struct FieldTemplate {
    
    let defaultField: [[Field]] = [
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockNone.rawValue, color: Color.gray), Field(type: BlockType.BlockHard.rawValue, color: Color.black)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),Field(type: BlockType.BlockHard.rawValue, color: Color.black),]
    ]
}

struct Field {
    var type: Int
    var color: Color
}
