//
//  FieldTemplate.swift
//  Tetorinu
//
//  Created by 広瀬友哉 on 2024/09/23.
//

import SwiftUI

struct FieldTemplate {
    
    let defaultField: [[Field]] = [
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockNone.rawValue, color: Color.black), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
        [Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white), Field(type: BlockType.BlockHard.rawValue, color: Color.white)],
    ]
}

struct Field {
    var type: Int
    var color: Color
}
